# -*- coding: utf-8 -*-
"""PROJET MACHINE  LEARNING

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdHtFIO8rfnHGZaCA-ICDtHrZOTG-mxr

# PROJET MACHINE  LEARNING

## Chargement des bibliothèques requises.
"""

import pandas as pd #permet de charger et de manipuler les donnees
import numpy as np # permet de faire des calculs scientifiques et des conversions
import matplotlib.pyplot as plt # permet de faire des representations graphiques
import seaborn as sns # visualiser des donnees
from collections import Counter
import itertools
import plotly.express as px #pour la partie data visualisation
from sklearn.preprocessing import  MinMaxScaler #normalisation des donnees
from sklearn.preprocessing import StandardScaler #representer les donnees dans l'intervalle [0.1]
from sklearn.model_selection import train_test_split #un module utile pour le fractionnement des données.
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, recall_score, f1_score #pour voir si les modeles entraines sont performants(taux de bonnes réponses).
from sklearn.linear_model import LogisticRegression #module pour creer un modele de régression logistique
from sklearn.ensemble import RandomForestClassifier #module pour effectuer un modèle de random forest.
from sklearn.tree import DecisionTreeClassifier #module pour creer un modèle d'arbe de decision.
from sklearn.svm import SVC #quand le modele est de type classification
from sklearn.neighbors import KNeighborsClassifier #modele knn de type classification
from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE

"""# Taches

## 1.Chargez les données et les stocker dans une variable df.
"""

df =pd.read_csv("diabetes.csv")
df.head()

"""- **Pregnancies** : Nombre de grossesses
- **Glucose** : Taux de glucose plasmatique (concentration de sucre dans le sang)
- **BloodPressure** : Pression artérielle diastolique (mm Hg)(Hypertension)
- **SkinThickness** : Épaisseur du pli cutané tricipital (en mm) ~ Sert à estimer la masse grasse corporelle
- **Insulin** : Taux d’insuline sérique (μU/ml)(L’insuline est l’hormone qui régule le glucose sanguin)
- **BMI(Body Mass Index)** : BMI(Indice de masse corporelle) = Poids / taille2 - Surpoids / obésité = facteur majeur de diabète type 2.
- **DiabetesPedigreeFunction** : Score génétique estimant la probabilité de diabète selon les antécédents familiaux
- **Age** : Âge en années
- **Outcome (Variable cible)**

## 2.Lister les différents modèles existants pour résoudre le problème ?

Cette phase en est la 1ere consistant a definir le probleme c-a-d, lister les differents modeles qu'on doit utiliser pour redoudre le probleme.

##Modele d'apprentissage supervisé:
- Type: Classification
  * regression logistique
  * Knn par classification
  * Svmpar classification
  * random forest par classification
  * Arbre de decision ou decision tree par classification

On va utiliser ces modeles car la variables de sortie est connue a l'avance et est de type classification {categoriel = binaire( 0 et 1) }

## 3. Implémenter la phase de la préparation des données (vérification des valeurs manquantes, aberrantes, doublons).
"""

df.shape #la dimension du dataset

df.describe() #permet de generer des statistiques descriptives pour un dataframe ou une serie

df.info()

# lister la valeur de la variable de sortie
len(df['Outcome'].unique())

df.Outcome.value_counts()

# Patient non_diabete
non_diabete = len(df[df['Outcome'] == 0])

# Patient diabétique
diabete = len(df[df['Outcome'] == 1])

# pourcentage
pourcentage_diabete = (diabete / (diabete + non_diabete)) * 100


print("Nombre de patients qui n'ont pas de diabéte: ", non_diabete)
print("Nombre de patient diabétique: ", diabete)
print("Percentage de diabétes: {:.4f}".format(pourcentage_diabete))

"""# - Verification des valeurs manquantes"""

df.isnull().sum()

"""On constate que le jeu de données ne contient pas de valeurs manquantes.

# - Verification des valeurs aberrantes

Colonnes concernées :

* Glucose(0 = impossible biologiquementmais ne sont pas extrêmes statistiquement)

* BloodPressure(0 = valeur biologiquement impossible mais ne sont pas extrêmes statistiquement)

* SkinThickness(0 = mesure manquante)

* Insulin(0 = valeur manquante)

* BMI(0 = biologiquement impossible mais ne sont PAS des outliers)

* Age(0 = impossible)
"""

#avec la variable Glucose
sns.boxplot(df['Glucose'])

"""On constate que la var Glucose contient de valeurs aberrantes mais aussi la distribution est asymetrique."""

#avec la variable BloodPressure
sns.boxplot(df['BloodPressure'])

"""On constate que la var BloodPressure contient de valeurs aberrantes mais aussi la distribution est asymetrique."""

#avec la variable SkinThickness
sns.boxplot(df['SkinThickness'])

"""On constate que la var SkinThickness contient de valeurs aberrantes mais aussi la distribution est asymetrique."""

#avec la variable Insulin
sns.boxplot(df['Insulin'])

"""On constate que la var Insulin contient de valeurs aberrantes mais aussi la distribution est asymetrique."""

#avec la variable BMI
sns.boxplot(df['BMI'])

"""On constate que la var BMI contient de valeurs aberrantes mais aussi la distribution est symetrique."""

#avec la variable age
sns.boxplot(df['Age'])

"""On constate que la var age contient de valeurs aberrantes mais aussi la distribution est asymetrique.

# correction des variables aberrantes

##Méthode BORNER (Winsorization avec IQR)
On limite les valeurs extrêmes aux bornes statistiques :
  - Lower=Q1−1.5×IQR
  - Upper=Q3+1.5×IQR
"""

df_new = df.copy()

variables = ['Glucose','Insulin','BloodPressure',
             'SkinThickness','BMI','Age']

for var in variables:

    q1 = df_new[var].quantile(0.25)
    q3 = df_new[var].quantile(0.75)

    interquantile = q3 - q1

    b_inf = q1 - 1.5 * interquantile
    b_sup = q3 + 1.5 * interquantile

    # BORNER (remplacer les valeurs)
    df_new[var] = df_new[var].clip(b_inf, b_sup)

#vérifier qu’il n’y a plus d’outliers apres bornage selon la même logique IQR
for var in variables:
    q1 = df_new[var].quantile(0.25)
    q3 = df_new[var].quantile(0.75)

    IQR = q3 - q1

    b_inf = q1 - 1.5*IQR
    b_sup = q3 + 1.5*IQR

    n_outliers = df_new[(df_new[var] < b_inf) | (df_new[var] > b_sup)].shape[0]
    print(var, n_outliers)

print(q1)
print(q3)
print(interquantile)

#Boxplot de toutes les variables

plt.figure(figsize=(12,6))
df.boxplot(column=['Glucose','Insulin','BloodPressure',
                   'SkinThickness','BMI','Age'])
plt.xticks(rotation=45)
plt.title("Boxplot - Avant correction")
plt.show()

#Boxplot après bornage

plt.figure(figsize=(12,6))
df_new.boxplot(column=['Glucose','Insulin','BloodPressure',
                       'SkinThickness','BMI','Age'])
plt.xticks(rotation=45)
plt.title("Boxplot - Après winsorisation")
plt.show()

#Comparaison côte à côte
fig, axes = plt.subplots(1, 2, figsize=(16,6))

df[['Glucose','Insulin','BloodPressure',
    'SkinThickness','BMI','Age']].boxplot(ax=axes[0])
axes[0].set_title("Avant correction")
axes[0].tick_params(axis='x', rotation=45)

df_new[['Glucose','Insulin','BloodPressure',
        'SkinThickness','BMI','Age']].boxplot(ax=axes[1])
axes[1].set_title("Après winsorisation")
axes[1].tick_params(axis='x', rotation=45)

plt.show()

"""# -Verification des doublons"""

df_new.duplicated().sum()

#afficher les doublons
df_new[df_new.duplicated()]

"""On peut conclure que le jeu de donnees ne contient pas de doublons

## - Standardisation

Moyenne = 0
Écart-type = 1
"""

# Séparer X et y
X = df_new.drop('Outcome', axis=1)
y = df_new['Outcome']

scaler = StandardScaler()
df_norme = scaler.fit_transform(X) #(df_new)

# Reconvertir en DataFrame
df_norme = pd.DataFrame(df_norme, columns = X.columns) #df_new.columns)
df_norme

"""#4. Séparer les donnes en deux parties la variable en entrée et la variable de sortie"""

# Variables d'entrée
X = df_new.drop("Outcome", axis=1)

# Variable de sortie
y = df_new['Outcome']

print("Shape de X :", X.shape)
print("Shape de y :", y.shape)

"""# 5. Divisez le jeu de données en deux partie (données d'entraînement et données de test) on considère 20% pour les données de test et 80% pour des données d’entrainements."""

# x_train et y_train :donnees d'entrainement
x_train, x_test, y_train, y_test = train_test_split(X, y,test_size= 0.2, random_state=42)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

"""# 6. Créez et entrainer les modèles lister en question 2.

## - creation et apprentissage du modele de regression logistique
"""

model_logist =  LogisticRegression() #creation du modele / instanciation de la classe
model_logist.fit(x_train,y_train) #entrainement des modeles

#Prediction des modeles
#on utilise sur cette phase les donnees de test
p_rl = model_logist.predict(x_test)
p_rl

Reg_logistic_score = model_logist.score(x_test, y_test) * 100
Reg_logistic_score

"""#Creation et apprentissage du modele knn par classification"""

modele_knn =  KNeighborsClassifier() #creation du modele / instanciation de la classe
modele_knn.fit(x_train, y_train) # entrainement du modele

#prediction du modele
predictions_knn = modele_knn.predict(x_test)
predictions_knn

modele_knn_score = modele_knn.score(x_test, y_test) * 100
modele_knn_score

"""#Creation et apprentissage du modele SVM par classification"""

modele_svm =  SVC() #creation du modele / instanciation de la classe
modele_svm.fit(x_train, y_train) #enteainement du modele

predictions_svm = modele_svm.predict(x_test)
predictions_svm

modele_svm_score = modele_svm.score(x_test, y_test) * 100
modele_svm_score

"""#|Creation et apprentissage du modele Arbre de decision par classification"""

# Decision Tree Classifier
decision_tree = DecisionTreeClassifier()
decision_tree.fit(x_train, y_train)

decision_tree

#prediction
predictions_dt = decision_tree.predict(x_test)

predictions_dt

#score
decision_tree_score = decision_tree.score(x_test, y_test) * 100
decision_tree_score

"""##Creation et apprentissage du modele Random forest par classification"""

random_forest = RandomForestClassifier(n_estimators= 100) #creation du modele / instanciation de la classe
random_forest.fit(x_train, y_train) #entrainement du modele

#prediction
predictions_rf = random_forest.predict(x_test)
predictions_rf

#score
random_forest_score = random_forest.score(x_test, y_test) * 100
random_forest_score

# Print scores of our classifiers

print("Regression logistic Score: ", Reg_logistic_score)
print("Random Forest Score: ", random_forest_score)
print("Decision Tree Score: ", decision_tree_score)
print("SVM Score: ", modele_svm_score)
print("knn Score: ", modele_knn_score)

"""#7. Evaluer chaque modèle entrainer en fonction des métriques.

##Matrice de confusion

## - Plot confusion matrix for logistic regression
"""

# The below function is directly taken from the scikit-learn website to plot the confusion matrix

def plot_confusion_matrix(cm, classes, normalize=False, title='Confusion Matrix', cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=0)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt), horizontalalignment="center", color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()

p_rl = model_logist.predict(x_test)

conf_matrix_rl = confusion_matrix(y_test, p_rl)
print(conf_matrix_rl)

plot_confusion_matrix(conf_matrix_rl, classes=[0, 1], title= "Confusion Matrix - Logistic regression")

"""- sur les 81+18 cas predits comme non diabetique, le modele a detecté 18 cas diabetique.
- sur les 19+36 cas predits comme diabetique, le modele a detecté 36 cas non diabetique

## - Plot confusion matrix for knn
"""

predictions_knn = modele_knn.predict(x_test)

conf_matrix_knn = confusion_matrix(y_test, predictions_knn)
print(conf_matrix_knn)

plot_confusion_matrix(conf_matrix_knn, classes=[0, 1], title= "Confusion Matrix - Knn")

"""## - Plot confusion matrix for Svm"""

predictions_svm = modele_svm.predict(x_test)

conf_matrix_svm = confusion_matrix(y_test, predictions_svm)
print(conf_matrix_svm)

plot_confusion_matrix(conf_matrix_svm, classes=[0, 1], title= "Confusion Matrix - SVM")

"""## - Plot confusion matrix for Decision tree"""

predictions_dt = decision_tree.predict(x_test)

conf_matrix_dt = confusion_matrix(y_test, predictions_dt)
print(conf_matrix_dt)

plot_confusion_matrix(conf_matrix_dt, classes=[0, 1], title= "Confusion Matrix - Decision tree")

"""## - Plot confusion matrix for random forest"""

predictions_rf = random_forest.predict(x_test)

conf_matrix_rf = confusion_matrix(y_test, predictions_rf)
print(conf_matrix_rf)

plot_confusion_matrix(conf_matrix_rf, classes=[0, 1], title= "Confusion Matrix - Random Forest")

"""##Interprétation des métriques"""

from sklearn.metrics import classification_report

#regression logistique

print(classification_report(y_test, p_rl))

#knn

print(classification_report(y_test, predictions_knn))

#svm
print(classification_report(y_test, predictions_svm))

#decision tree
print(classification_report(y_test, predictions_dt))

#randon forest
from sklearn.metrics import classification_report

print(classification_report(y_test, predictions_rf))

"""## 🔹 Accuracy(TP+TN /TOTAL):
 * Trompeur si classes déséquilibrées

## 🔹 Precision(TP / TP+FP):
  *Parmi ceux prédits diabétiques, combien le sont réellement ?

## 🔹 Recall(TP / TP+FN):
  * Parmi les vrais diabétiques, combien ont été détectés ?

## 🔹 F1-score(Moyenne harmonique Precision + Recall):
  * Bon compromis global

"""

#Évaluer tous les modèles automatiquement
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

models = {
    "Logistic Regression": model_logist,
    "Random Forest": random_forest,
    "Decision Tree": decision_tree,
    "SVM": modele_svm,
    "KNN": modele_knn
}

for name, model in models.items():
    y_pred = model.predict(x_test)

    print("\n", name)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred))
    print("Recall:", recall_score(y_test, y_pred))
    print("F1-score:", f1_score(y_test, y_pred))

#ou utiliser cette methode pour evaluer chaque modele
# The below function prints the following necesary metrics

def metrics(actuals, predictions):
    print("Accuracy: {:.5f}".format(accuracy_score(actuals, predictions)))
    print("Precision: {:.5f}".format(precision_score(actuals, predictions)))
    print("Recall: {:.5f}".format(recall_score(actuals, predictions)))
    print("F1-score: {:.5f}".format(f1_score(actuals, predictions)))

print("Evaluation of Random Forest Model")
print()
metrics(y_test, predictions_rf.round())

"""#8. Faite une étude de comparaisons des différents modèles implémentés sur la base des métriques.

| Modèle              | Accuracy   | Precision  | Recall     | F1-score   |
| ------------------- | ---------- | ---------- | ---------- | ---------- |
| Logistic Regression | 0.7597     | 0.6667     | 0.6545     | 0.6605     |
| Random Forest       | 0.7338     | 0.6296     | 0.6182     | 0.6239     |
| Decision Tree       | 0.7532     | 0.6308     | **0.7455** | **0.6833** |
| **SVM**             | **0.7662** | **0.7209** | 0.5636     | 0.6327     |
| KNN                 | 0.6688     | 0.5323     | 0.6000     | 0.5641     |

**Analyse détaillée**

1. **Accuracy** (performance globale)

Le meilleur modèle est : **SVM** (0.7662)

Mais l’accuracy seule n’est pas suffisante en santé.

2. **Precision** (réduction des faux positifs)

La meilleure precision : **SVM** (0.7209)

Cela signifie quand SVM prédit "diabétique", il a raison 72% du temps.

Donc peu de faux positifs.

3. **Recall** (détection des diabétiques)

Le meilleur recall est **Decision Tree (0.7454)**

Très important en médecine.

Recall = capacité à détecter les vrais malades.

Donc Decision Tree rate moins de patients diabétiques.

4. **F1-score** (équilibre précision / rappel)

Le meilleur F1-score : **Decision Tree (0.6833)**

F1 est crucial quand les classes sont déséquilibrées.
**texte en gras**

## ***Interprétation métier (très important)***

Dans un contexte médical :
  * Faux négatif (diabétique non détecté) = grave

  * Faux positif = moins grave (examen complémentaire possible)

Donc, le Recall est prioritaire.

Le modèle qui détecte le plus de diabétiques : **Decision Tree**

## ***Quel modèle choisir ?***
🔹 Si on privilégie la performance globale : **SVM**

🔹 Si on privilégie la sécurité médicale : **Decision Tree**

🔹 Si on veut un modèle stable, interprétable et robuste : **Logistic Regression**

Pourquoi ?

Performance proche du meilleur, stable, interprétable, moins sujet à l’overfitting et simple à déployer

## **Conclusion**
L’étude comparative des modèles montre que le SVM obtient la meilleure accuracy (76.6%) et la meilleure precision (72%), tandis que l’arbre de décision présente le meilleur recall (74.5%) et le meilleur F1-score (68.3%).

Dans un contexte médical où la détection des patients diabétiques est prioritaire, le recall constitue un critère déterminant.

Toutefois, la régression logistique offre un bon compromis entre performance, stabilité et interprétabilité, ce qui en fait un modèle adapté pour un déploiement en environnement réel.

#constat
Le modèle  **régression logistique** fonctionne mieux que  les arbres de décision et SVM.

Mais, si nous observons clairement que notre ensemble de données souffre d'un sérieux problème de **déséquilibre de classe**.
Les patients non diabetiques représentent plus de 65 % du dataset et les patients diabetiques constituent 35 %.

Avec ce type de distribution, si nous entraînons notre modèle sans tenir compte des problèmes de déséquilibre, il prédit l'étiquette avec une plus grande importance de donnée aux patients non diabetiques (car il y a plus de données à leur sujet) et obtient donc plus de précision.

Le problème de déséquilibre de classe peut être résolu par diverses techniques. Le **suréchantillonnage** en fait partie.

Une approche pour traiter les ensembles de données déséquilibrés consiste à suréchantillonner la classe minoritaire. L'approche la plus simple consiste à dupliquer des exemples dans la classe minoritaire, bien que ces exemples n'ajoutent aucune nouvelle information au modèle.

Au lieu de cela, de nouveaux exemples peuvent être synthétisés à partir des exemples existants. Il s’agit d’un type d’augmentation de données pour la classe minoritaire et est appelé **technique de suréchantillonnage synthétique des minorités**, ou **SMOTE** en abrégé.
"""

from sklearn.metrics import classification_report
from imblearn.over_sampling import SMOTE

#Split d’abord (80% train / 20% test)
#Appliquer SMOTE uniquement sur le train
#tester sur le test original

# 1 Split initial
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Distribution avant SMOTE:", Counter(y_train))

"""0: non diabetique
1:diabetique
"""

# 2 Appliquer SMOTE seulement sur le train
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print("Distribution après SMOTE:", Counter(y_train_resampled))

"""###Logistique regression"""

# 3 Entraîner le modèle
rl_resampled = LogisticRegression()
rl_resampled.fit(X_train_resampled, y_train_resampled)

# 4 Prédictions
predictions_resampled_rl = rl_resampled.predict(X_test)

#score
logistic_regression_score_resampled = rl_resampled.score(X_test, y_test) * 100
logistic_regression_score_resampled

# 5 Matrice de confusion
rl_cm_resampled = confusion_matrix(y_test, predictions_resampled_rl)

print("Confusion Matrix - Logistic regresssion After SMOTE")
print(rl_cm_resampled)

print(classification_report(y_test, predictions_resampled_rl))

plot_confusion_matrix(rl_cm_resampled, classes=[0, 1], title= "Confusion Matrix - Logistic regression After Oversampling")

"""###decision tree"""

# 3 Entraîner le modèle
dt_resampled = DecisionTreeClassifier()
dt_resampled.fit(X_train_resampled, y_train_resampled)

# 4 Prédictions
predictions_resampled_dt = dt_resampled.predict(X_test)

#score
dt_score_resampled =dt_resampled.score(X_test, y_test) * 100
dt_score_resampled

# 5 Matrice de confusion
dt_cm_resampled = confusion_matrix(y_test, predictions_resampled_dt)

print("Confusion Matrix - Decision tree After SMOTE")
print(dt_cm_resampled)

print(classification_report(y_test, predictions_resampled_dt))

plot_confusion_matrix(dt_cm_resampled, classes=[0, 1], title= "Confusion Matrix - Decision tree After Oversampling")

"""##SVM"""

# 3 Entraîner le modèle
svm_resampled = SVC()
svm_resampled.fit(X_train_resampled, y_train_resampled)

# 4 Prédictions
predictions_resampled_svm = svm_resampled.predict(X_test)

#score
svm_score_resampled = svm_resampled.score(X_test, y_test) * 100
svm_score_resampled

# 5 Matrice de confusion
svm_cm_resampled = confusion_matrix(y_test, predictions_resampled_svm)

print("Confusion Matrix - SVM After SMOTE")
print(svm_cm_resampled)

print(classification_report(y_test, predictions_resampled_svm))

plot_confusion_matrix(svm_cm_resampled, classes=[0, 1], title= "Confusion Matrix - SVM After Oversampling")

"""##KNN"""

# 3 Entraîner le modèle
knn_resampled = KNeighborsClassifier()
knn_resampled.fit(X_train_resampled, y_train_resampled)

# 4 Prédictions
predictions_resampled_knn = knn_resampled.predict(X_test)

#score
knn_score_resampled = knn_resampled.score(X_test, y_test) * 100
knn_score_resampled

# 5 Matrice de confusion
knn_cm_resampled = confusion_matrix(y_test, predictions_resampled_knn)

print("Confusion Matrix - Knn After SMOTE")
print(knn_cm_resampled)

print(classification_report(y_test, predictions_resampled_knn))

plot_confusion_matrix(knn_cm_resampled, classes=[0, 1], title= "Confusion Matrix - Knn After Oversampling")

"""###Random forest"""

# 3 Entraîner le modèle
rf_resampled = RandomForestClassifier(n_estimators=100, random_state=42)
rf_resampled.fit(X_train_resampled, y_train_resampled)

# 4 Prédictions
predictions_resampled_rf = rf_resampled.predict(X_test)

#score
rf_score_resampled = rf_resampled.score(X_test, y_test) * 100
rf_score_resampled

# 5 Matrice de confusion
rf_cm_resampled = confusion_matrix(y_test, predictions_resampled_rf)

print("Confusion Matrix - Random Forest After SMOTE")
print(rf_cm_resampled)

print(classification_report(y_test, predictions_resampled_rf))

plot_confusion_matrix(rf_cm_resampled, classes=[0, 1], title= "Confusion Matrix - Random Forest After Oversampling")

# The below function prints the following necesary metrics

def metrics(actuals, predictions):
    print("Accuracy: {:.5f}".format(accuracy_score(actuals, predictions)))
    print("Precision: {:.5f}".format(precision_score(actuals, predictions)))
    print("Recall: {:.5f}".format(recall_score(actuals, predictions)))
    print("F1-score: {:.5f}".format(f1_score(actuals, predictions)))

print("Evaluation of logistic regression Model")
print()
metrics(y_test, predictions_resampled_rl.round())

print("Evaluation of Decistion tree Model")
print()
metrics(y_test, predictions_resampled_dt.round())

print("Evaluation of Random Forest Model")
print()
metrics(y_test, predictions_resampled_rf.round())

print("Evaluation of SVM Model")
print()
metrics(y_test, predictions_resampled_svm.round())

print("Evaluation of Knn Model")
print()
metrics(y_test, predictions_resampled_knn.round())

"""##Resultat apres SMOTE

| Modèle              | Accuracy   | Precision  | Recall     | F1-score   |
| ------------------- | ---------- | ---------- | ---------- | ---------- |
| Logistic Regression | 0.7426     | 0.60938     | **0.7222** | 0.66102     |
| Decision Tree       | 0.72727     | 0.62000     | 0.57407     | 0.59615     |
| Random Forest       | **0.75974** | **0.64407** | 0.70370     | **0.67257** |
| SVM                 | 0.68831     | 0.54545     | 0.66667     | 0.6000     |
| KNN                 | 0.6623     | 0.51429     | 0.6667     | 0.58065     |


changement apres rectification

L’étude comparative des modèles avant et après application de la technique SMOTE montre que la correction du déséquilibre de classes améliore significativement la capacité de détection des patients diabétiques (augmentation du recall).

Après suréchantillonnage, le Random Forest présente le meilleur compromis global avec une accuracy de 75.97% et un F1-score de 67.25%.

La Régression Logistique conserve également de bonnes performances et offre une meilleure interprétabilité, ce qui la rend pertinente pour un contexte médical.

L’utilisation de SMOTE permet donc de réduire le biais lié au déséquilibre de classe et d’améliorer la robustesse des modèles.

#9. Sauvegarder le meilleur modèle.

joblib est plus adapté que pickle pour les modèles sklearn.
"""

#Sauvegarder le pipeline complet

import joblib

joblib.dump(rf_resampled, "best_model_diabetes.pkl")

print("Modèle Random Forest sauvegardé avec succès !")

import os
print("Taille du fichier :", os.path.getsize("best_model_diabetes.pkl"), "bytes")

columns = x_train.columns.tolist()
joblib.dump(columns, "model_columns.pkl")

#Charger le modèle plus tard
loaded_model = joblib.load("best_model_diabetes.pkl")

prediction = loaded_model.predict(X_test)
#prediction

#Version de sklearn
import sklearn
print(sklearn.__version__)

"""Le modèle a été entraîné et sauvegardé avec scikit-learn version 1.6.1 afin d'assurer la reproductibilité.

***Conclusion pour la question 9***

Après application de la technique SMOTE pour corriger le déséquilibre des classes, le modèle Random Forest a présenté le meilleur compromis entre accuracy et F1-score.

Le modèle final a été entraîné sur les données d’apprentissage suréchantillonnées, puis sauvegardé à l’aide de la bibliothèque joblib afin de permettre son déploiement ultérieur.

#10. Déployer le meilleur modèle (vous pouvez utilise flask pour la création du serveur Backend et HTML,CSS et JavaScript pour la partie frontend).

Le modèle retenu (Random Forest) a été déployé à l’aide du framework web Flask.

Le backend charge le pipeline sauvegardé incluant la standardisation des données.

Le frontend a été développé en HTML et CSS afin de permettre la saisie interactive des variables cliniques.

L’application retourne la prédiction ainsi que la probabilité associée, permettant une interprétation plus fine du risque.
"""